[package]
name = "motorserver"
version = "0.1.0"
authors = ["Mitchell Bruckner <mbruckner807@gmail.com>"]
edition = "2018"

[dependencies]
motor = {path = "../motor" }
actix-web = "0.7"
serde_derive = "*"
serde = "*"
