[package]
name = "motor"
version = "0.1.0"
authors = ["Mitchell Bruckner <mbruckner807@gmail.com>"]
edition = "2018"

[dependencies]
serial = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
